spring:
  #配置DataSource
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cxcy?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    #热部署静态文件
    cache: false
    #配置页面标准格式
    encoding: utf-8
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:templates/
    #配置标准
  #配置JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
  jackson:
    time-zone: GMT+8

  #配置搜索引擎
 # data:
    #elasticsearch:
      #cluster-nodes: localhost:9300
server:
  port: 8080
  #文件上传限制



img:
  location: D:/upload/
  imagesPath: file:/D:/upload/





