spring:
  #配置DataSource
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cxcy?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    #热部署静态文件
    cache: false
    #配置页面标准格式
    encoding: utf-8
    #配置标准,不强制要求/结尾
    mode: LEGACYHTML5
    prefix: classpath:/templates/

    #配置标准

    content-type: text/html
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
      enabled: true
  #配置JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #配置搜索引擎
 # data:
    #elasticsearch:
      #cluster-nodes: localhost:9300
file:
  FilePath: E:/Workspace/Temp/file/


video:
  VideoPath: file:/E:/temp/
server:
  port: 8081



